<?php include "header.php" ?>
<div class="container">
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #ECEEEF;"><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">	<span class="navbar-toggler-icon"></span></button>
<a class="navbar-brand" href="http://localhost/olharcidadao/">	<img src="http://localhost/olharcidadao/imagens/icon.png" width="30" height="200" class="d-inline-block align-top" alt="">&ensp; OLHAR CIDADÃO &ensp;&ensp;&ensp;&ensp;</a><div class="collapse navbar-collapse" id="navbar">	<ul class="navbar-nav mr-auto mt-2 mt-md-0">		<?php if(!isset($_SESSION['usuario_nome']))			{?>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/"><b>Início</b></a></li>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/painel"><b>Entrar</b></a></li>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/cadastrar"><b>Cadastrar</b></a></li>			<?php } else {?>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/"><b>Início</b></a></li>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/painel"><b>Minhas Publicações</b></a></li>			<li class="nav-item"><a class="nav-link" href="http://localhost/olharcidadao/sair"><b>Sair</b></a></li>		<?php }?>	</ul>
	<form class="form-inline my-2 my-lg-0" action="http://localhost/olharcidadao/buscar/todos" method="post">		<input class="form-control mr-sm-2" type="text" placeholder="Palavras-chave..." id="keyword" name="keyword" required><br>		<button class="btn btn-outline-info my-2 my-sm-0" type="submit">Buscar <i class="fa fa-search" aria-hidden="true"></i></button>	</form>
</div></nav><br>
</div>

<div class="container">
<div class="row">
	<div class="col-sm-7">
	<?php if (isset($results)) {		if($results=='Nenhuma publicação cadastrada!')		{ ?>		<div class="alert alert-danger" role="alert">		<center> Atenção!   <?php echo $results; ?></center>		</div>		<?php }		else{		foreach ($results as $value) {		?>	<center>	<div class="card">	<div class="card-block">	<h4 class="card-title"><?php echo $value->titulo;?></h4>	<h6 class="card-subtitle text-muted"><strong><?php echo date('d/m/Y', strtotime( $value->curr_time));?></strong></h6>	<center><br /><img src="<?php echo base_url().$value->foto; ?>"/></center><br />	<div align="center"><a href="http://localhost/olharcidadao/inicio/publicacao/<?php echo $value->id ?>" class="btn btn-success btn-lg btn-block">Ver Publicação &raquo;</a></div>	</div>	</div><br />	</center>	<?php }}}?>	</div></div></div>
<?php include "footer.php"?>
